In [2]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [29]:
Original_list = [12.23, 13.32, 100, 36.32]
arr = np.array(Original_list)
print(arr)

[ 12.23  13.32 100.    36.32]


2.Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [23]:
arr = np.arange(2, 11).reshape(3, 3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [10]:
original_array = np.zeros((10))
print(original_array)
original_array[6] = 11
print(original_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [28]:
original_array = np.arange(12, 38)

print("Original array : ",original_array)

x = original_array[::-1]
print("Reverse array :", x)

Original array :  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array : [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [43]:
Original_List = np.ones((5,5))
print(Original_List)
Original_List[1:-1,1:-1] = 0

print(Original_List)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]


In [35]:
original_array = np.ones((3, 3))
Array2 = np.zeros((5, 5))
Array2[1:4, 1:4] = original_array 

print(Array2)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


77. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [42]:
matrix = np.zeros((8, 8),dtype=int)
print(matrix)
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print( matrix)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [52]:
list = [1,2, 3, 4, 5, 6, 7, 8]
arry = np.array(list)
print(type(list))
print("List to array :", arry)


tuple = ([8, 4, 6], [1, 2, 3])
arry2 = np.array(tuple)
print("Tuple to array :", arry2)

<class 'list'>
List to array : [1 2 3 4 5 6 7 8]
Tuple to array : [[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [59]:
array = np.array([10, 20, 30])
print("Original array:", array)

new_arry = np.append(array, [40, 50, 60, 70, 80, 90])
print("After append values to the end of the array:", new_arry)

Original array: [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


10. 10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]


In [61]:
arr = np.array([1 + 0j, 0.70710678 + 0.70710678j])
real_part = arr.real
imag_part = arr.imag
print("Real part of the array:", real_part)
print("Imaginary part of the array:", imag_part)

Real part of the array: [1.         0.70710678]
Imaginary part of the array: [0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [62]:
Array1 = np.array([0, 10, 20, 40, 60])
Array2 = np.array([10, 30, 40])
common_values = np.intersect1d(Array1, Array2)
print("Common values between two arrays:", common_values)

Common values between two arrays: [10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]


In [65]:
Array1 = np.array([0, 10, 20, 40, 60, 80])

Array2 = np.array([10, 30, 40, 50, 70, 90])

set_difference = np.setdiff1d(Array1, Array2)

print("Set difference between two arrays:", set_difference)

Set difference between two arrays: [ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [66]:
Array1 = np.array([0, 10, 20, 40, 60, 80])
Array2 = np.array([10, 30, 40, 50, 70])
u_array = np.setxor1d(Array1, Array2)
print("Unique values that are in only one (not both) of the input arrays:", u_array)

Unique values that are in only one (not both) of the input arrays: [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]



In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])

print(a > b)   
print(a >= b)  
print(a < b)   
print(a <= b)




[False False]
[False False]
[ True  True]
[ True  True]


15. Write a Python program to save a NumPy array to a text file.


In [68]:
arr = np.array([10, 20, 30])
np.savetxt("array.txt", arr, fmt="%d")


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [69]:
arr = np.array([[10, 20, 30], [20, 40, 50]])
flat_arr = arr.ravel()
print(flat_arr) 


[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [70]:
arr = np.array([[2, 4, 6], [6, 8, 10]], dtype=np.int32)
print(arr.dtype)

new_arr = arr.astype(np.float64)
print(new_arr)


int32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [71]:
arr = np.eye(3) 
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]]

In [76]:

matrix = np.tri(4, 3, -1)

print(matrix)




[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]])

In [79]:
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])

concat_arr = np.hstack((arr1, arr2))  # Horizontally stack
print(concat_arr)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [83]:
arr = np.array([10, 20, 30])
arr.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")

arr[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [85]:
arr = np.arange(12).reshape(3, 4)
new_arr = arr * 3
print("New array elements :", new_arr)


New array elements : [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [86]:
arr = np.array([[0, 1], [2, 3], [4, 5]])
list_arr = arr.tolist()
print("Array to list :",list_arr)


Array to list : [[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:

Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [ ]:
arr = np.random.rand(10) 
np.set_printoptions(precision=3)
print(arr)


[0.575 0.145 0.569 0.631 0.935 0.479 0.293 0.042 0.088 0.302]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]

In [92]:
arr = np.array([1.6e-10, 1.6, 1200, 0.235])
np.set_printoptions(suppress=True, precision=3)
print(arr)


[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [93]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
extra_column = np.array([[100], [200]])

new_arr = np.hstack((arr, extra_column))
print(new_arr)


[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]

In [94]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
new_arr = np.delete(arr, [0, 3, 4])  
print(new_arr)  


[ 20  30  60  70  80  90 100]
